### ISSUE TITLE
how to use raidsv.txt and preset.txt

### ISSUE THREAD

**Issue by zbyshuai** [Manu098vm/SysBot.NET#1]
Hello！I have a few questions regarding the sv raid-bot aspect of sysbot that I would like to inquire about:

Are there any relevant tutorials available for raids? Currently, I'm exploring on my own, but there are many things I don't understand.

How should I set up sysbot and how should I fill in the raidsv.txt to make them effective? Currently, I've filled in raidsv.txt with two sets of raids in the format seed-specie-star, but in the actual game, the Pokémon in front of me have not been replaced with the ones from raidsv.txt.

How should I set up sysbot and how should I fill in the contents of the preset document? Currently, after starting my sysbot, the game can cycle through raids, but no information appears in Discord. I hope to achieve the effect of embedding in the channel.

Thank you for taking the time to answer these questions amidst your busy schedule.

**Comment by Manu098vm** [comment]
I'm not sure there's a full guide out there, but you can eventually take a look at these pages:
https://pastebin.com/2XeK9Vf4
https://github.com/zyro670/NotForkBot.NET/wiki/2.-RaidBot-SV
