### ISSUE TITLE
Issue with bot

### ISSUE THREAD

**Issue by Joseph11024** [Manu098vm/SysBot.NET#2]
Hey idk if there is a fix for this or if it’s already in the works but the latest commits for pkhex for the past couple of weeks do not work with the bot. This is the error I get when trying to start the bot…

Method not found: ‘Boolean
PkHex.Core.EncounterEvent.Get_Initialized()’.

Any ideas on how to remedy this any help would be greatly appreciated.

**Comment by Manu098vm** [comment]
Updating the dependencies also requires to update the API calls to those dependencies within the application code and all the other dependencies that uses the impacted APIs.
Updating the PKHeX.Core dependency by drag & drop only works when there's no modification to its API usage.

**Comment by Joseph11024** [comment]
How would I go about updating the APIs. I have no experience coding but I’ve been figuring out things little by little. This is my first time running into this issue. Sent from my iPhoneOn Sep 4, 2023, at 1:16 PM, Manu ***@***.***> wrote:﻿
Closed #2 as completed.

**Comment by Manu098vm** [comment]
Add the updated dependency in the deps folder, try to compile the program and see where it fails.
Try to fix the api method calls by looking at the pkhex source code.
You may have to do the same on the ALM dependency before updating the Sysbot codebase.

**Comment by Joseph11024** [comment]
Ok I don’t know if I have enough experience to do all of that but I will definitely give it a try. I appreciate the info. Any plans in updating the bot on your end or are you waiting for DLC before updating. Seems only merge bot is currently working with these new updates. Sent from my iPhoneOn Sep 4, 2023, at 1:34 PM, Manu ***@***.***> wrote:﻿
Add the updated dependency in the deps folder, try to compile the program and see where it fails.
Try to fix the api method calls by looking at the pkhex source code.
You may have to do the same on the ALM dependency before updating the Sysbot codebase.

**Comment by Manu098vm** [comment]
If I say I have plans on updating this fork I would give you expectations.

I have no plans. I may work on it or I may not. This is a hobby project, not something I work full time on.

If or when I have the time and the motivation to do it, then I will.

I don't want to give expectations anytime soon.

**Comment by Joseph11024** [comment]
Ok completely understandable. If it’s not too much to ask if you do end up working on it could you show me what I need to do? I know it’s a big ask I’m just trying to learn as much as I can so eventually I can do all of this myself. Completely understand if you don’t want to do that or do not have the time just thought I would ask. Sent from my iPhoneOn Sep 4, 2023, at 2:05 PM, Manu ***@***.***> wrote:﻿
If I say I have plans on updating this fork I would give you expectations.
I have no plans. I may work on it or I may not. This is a hobby project, not something I work full time on.
If or when I have the time and the motivation to do it, then I will.
I don't want to give expectations anytime soon.

**Comment by Manu098vm** [comment]
You can see and analyze any commit when they're pushed here on the github repository.
This is how github works :)

**Comment by Joseph11024** [comment]
Yes that’s how I’ve learned most things so far. I appreciate it. Sent from my iPhoneOn Sep 4, 2023, at 2:20 PM, Manu ***@***.***> wrote:﻿
You can see and analyze any commit when they're pushed here on the github repository.
This is how github works :)
