### ISSUE TITLE
Bot won’t select link trade on start up

### ISSUE THREAD

**Issue by Joseph11024** [Manu098vm/SysBot.NET#4]
When initially starting the bot when it opens the Poke portal it stays on union room instead of moving down to link trade. You have to manually move it down to link trade on the first go around and then it works fine unless it has to exit out of game in which case it runs into the same problem. I have tried to fix this myself by adding 2 DDown clicks to the code. This fixed the initial start up however, when it completes a trade the cursor is already on link trade and the 2 down clicks I added make it go down and select a different option. Just hoping you may be able to fix this or tell me how to fix it where it only does the 2 down clicks on initial start up and not on every loop.

**Comment by Manu098vm** [comment]
The bot isn't updated for the game update v2.1.0
You probably tried a bad pointer and it can't reliably detect the PokéPortal status.
Not an issue with the bot, please wait watiently for a new release for v2.1.0.
No ETA.

**Comment by Joseph11024** [comment]
Ok I’ve updated it for 2.0.1 already. I’ll try different pointer for poke portal status 👍
